name: GenesisMC
version: '${version}'
main: me.purplewolfmc.genesismc.GenesisSpigotMC
api-version: 1.19
authors: [ PurpleWolfMC ]
description: Genesis Plugin for SpigotMC
website: https://twitch.tv/PurpleWolfMC
commands:
  origins:
    description: Main Origins Directory
  origins-op:
    permission: purplewolf.genesismc.spigotmc.op
    description: operator command for genesismc
  beta:
    description: genesis beta
    permission: purplewolf.genesismc.spigotmc.beta