name: GenesisMC
version: '${version}'
main: me.purplewolfmc.genesismc.GenesisMC
api-version: 1.19
authors: [ PurpleWolfMC ]
description: Genesis Plugin for SpigotMC
website: https://twitch.tv/PurpleWolfMC
commands:
  origins:
    description: Main Origins Directory
    aliases:
      - genesismc
  beta:
    description: genesis beta
    permission: purplewolf.genesismc.spigotmc.beta
permissions:
  genesismc.origins.purge:
    default: op
  genesismc.origins.reload:
    default: op