name: OriginsSpigotMC
version: '${version}'
main: me.purplewolfmc.originsspigotmc.OriginsSpigotMC
api-version: 1.19
authors: [ PurpleWolfMC ]
description: Origins Plugin for SpigotMC
website: https://twitch.tv/PurpleWolfMC
commands:
  origins:
    description: Main Origins Directory
  origins-op:
    permission: purplewolf.origins.spigotmc.op
    description: operator command for origins
  beta:
    description: origins beta
    permission: purplewolf.origins.spigotmc.beta